/**
 * Output rendering: `pretty` (terminal), `json` (machines), and the Markdown
 * issue comment used by the GitHub Action.
 */
import pc from 'picocolors';
import { COMMENT_MARKER } from './github.js';
import type { AnalysisResult } from './types.js';

export interface FormatOptions {
  /** Enable ANSI colors (default false; the CLI passes isTTY). */
  color?: boolean;
}

function issueRef(result: AnalysisResult): string {
  const number = result.issue.number !== undefined ? `#${result.issue.number} ` : '';
  return `${number}"${result.issue.title}"`;
}

/** Stable, indented JSON — the machine-readable output. */
export function formatJson(result: AnalysisResult): string {
  return JSON.stringify(result, null, 2);
}

/** Human-readable terminal report. */
export function formatPretty(result: AnalysisResult, options: FormatOptions = {}): string {
  const c = pc.createColors(options.color ?? false);
  const lines: string[] = [];

  lines.push(c.bold(`triagekit v${result.meta.version}`) + c.dim(` — ${issueRef(result)}`));
  lines.push('');

  lines.push(c.bold('Suggested labels'));
  if (result.labels.length === 0) {
    lines.push(c.dim('  (no confident suggestion — needs human triage)'));
  } else {
    for (const suggestion of result.labels) {
      const tag = suggestion.source === 'llm' ? c.magenta(' [llm]') : '';
      lines.push(
        `  ${c.cyan(suggestion.label.padEnd(9))}${suggestion.confidence.toFixed(2)}${tag}  ${c.dim(
          suggestion.reasons.join('; '),
        )}`,
      );
    }
  }
  lines.push('');

  lines.push(
    c.bold('Possible duplicates') +
      c.dim(
        ` (scanned ${result.meta.existingIssuesScanned} issues, threshold ${result.meta.threshold})`,
      ),
  );
  if (result.duplicates.length === 0) {
    lines.push(c.dim('  none found'));
  } else {
    for (const candidate of result.duplicates) {
      lines.push(
        `  ${c.yellow(`#${candidate.number}`)}  ${candidate.score.toFixed(2)}  ${candidate.title}`,
      );
    }
  }
  lines.push('');

  const present = result.repro.fields.length - result.repro.missing.length;
  const note = result.repro.applicable ? '' : c.dim('  (not a bug report — informational)');
  lines.push(c.bold('Reproduction checklist') + ` [${present}/${result.repro.fields.length}]` + note);
  for (const field of result.repro.fields) {
    if (field.present) {
      const evidence = field.evidence ? c.dim(`  (${field.evidence})`) : '';
      lines.push(`  ${c.green('+')} ${field.label}${evidence}`);
    } else {
      lines.push(`  ${c.red('-')} ${field.label}  ${c.dim(field.hint)}`);
    }
  }

  if (result.llm.requested) {
    lines.push('');
    lines.push(
      result.llm.used
        ? c.dim(`LLM refinement: used (${result.llm.provider})`)
        : c.dim(`LLM refinement: skipped${result.llm.error ? ` — ${result.llm.error}` : ''}`),
    );
  }

  return lines.join('\n');
}

/** Markdown report posted as an issue comment by the GitHub Action. */
export function formatComment(result: AnalysisResult): string {
  const lines: string[] = [];
  lines.push('### triagekit report');
  lines.push('');

  const top = result.labels[0];
  if (top) {
    lines.push(
      `**Suggested label:** \`${top.label}\` (confidence ${top.confidence.toFixed(2)}) — ${top.reasons.join('; ')}`,
    );
  } else {
    lines.push('**Suggested label:** none — this issue needs human triage.');
  }
  lines.push('');

  if (result.duplicates.length > 0) {
    lines.push('**Possible duplicates:**');
    for (const candidate of result.duplicates) {
      lines.push(`- #${candidate.number} — ${candidate.title} (similarity ${candidate.score.toFixed(2)})`);
    }
  } else {
    lines.push(
      `**Possible duplicates:** none found (scanned ${result.meta.existingIssuesScanned} open issues).`,
    );
  }
  lines.push('');

  if (result.repro.applicable) {
    if (result.repro.missing.length === 0) {
      lines.push(
        '**Reproduction info:** all four elements present (version, OS, steps, expected vs actual) — thank you!',
      );
    } else {
      lines.push(
        '**Reproduction info missing** — to help maintainers reproduce this, please edit the issue and add:',
      );
      for (const field of result.repro.missing) {
        lines.push(`- [ ] **${field.label}** — ${field.hint}`);
      }
    }
    lines.push('');
  }

  lines.push(
    `<sub>Generated by <a href="https://github.com/kero168/triagekit">triagekit</a> v${result.meta.version}. Suggestions are heuristics — maintainers make the final call.</sub>`,
  );
  lines.push('');
  lines.push(COMMENT_MARKER);
  return lines.join('\n');
}
